# GitHub Actions 的名称
name: docker build
# 当 master 分支发生 push 或者 pull request 事件时触发 action
on:
    push:
        branches: [ main,dev ]
    pull_request:
        branches: [ main ]
# 指定 jobs
jobs:
    # build job
    build:
        # 指定运行在 ubuntu 上
        runs-on: ubuntu-latest
        steps:
            # 把仓库代码拉到 ubuntu 镜像上
            - uses: actions/checkout@v2
            - name: Npm package
              run: pwd && npm install && npm run build
            - name: Docker login
              uses: docker/login-action@v1
              with:
                  registry: ${{ secrets.DOCKER_REPOSITORY }}
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_SECRET }}
            - name: Docker build
              run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}/fyzzz/pan-server:latest .
            - name: Docker push
              run: docker push ${{ secrets.DOCKER_REPOSITORY }}/fyzzz/pan-server:latest
